version: '2'
services:
  redcap:
    container_name: redcap
    image: andy123/redcap-docker
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - "./www:/redcap_webroot"
      - "./mysql:/var/lib/mysql"
      - "./logs:/var/log/export"
    links:
      - "mailhog:mailhog"
      - "db:mysql"
    depends_on:
      - mailhog
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"
      - "81:8025"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwordMySQL
      MYSQL_USER: redcapnea
      MYSQL_PASSWORD: passwordMySQL
      MYSQL_DATABASE: chariotredcapdb
